### ISSUE TITLE
Github pages?

### ISSUE THREAD

**Issue by esbrandt** [mixxxdj/website#1]
What about moving to [Github pages](http://pages.github.com/)?
Hosted directly from the GitHub repository. Just edit, push, and changes are live. 
It works with a custom domain too, and would allow to go multi-lingual.

We could even make the binaries available, thus potentially reducing traffic and hosting costs.

**Comment by ywwg** [comment]
Where do they talk about available bandwidth?  I'd want to know how much data we can push before switching over.

**Comment by esbrandt** [comment]
> Where do they talk about available bandwidth?

Cant find any figures. But they encourage you to host the binaries. https://github.com/blog/1547-release-your-software

Tested this for the manual, see https://github.com/mixxxdj/manual/releases . The disadvantage seems to be, that you don`t have any stats. Maybe the mixxxdj org admin can see more?

Alternatively:
- Only host the static html on GH pages, Link binaries as before (avoids further dependencies)
- Host static html on GH pages, deliver trough CDN like https://bintray.com
- Waddaya talking about, we have plenty of bandwidth, changes are superfluous

**Comment by rryan** [comment]
Implementing /wiki and /forums would get complicated. We'd have to make mixxx.org DNS-resolve to GitHub but then somehow get GitHub to re-direct /wiki and /forums to our server. 

Also we probably wouldn't get Google Analytics? That's very useful for demographic information (who is visiting our site, the type of computer they are on, etc.)

Traffic costs for downloads is $2 / month right now for downloads.mixxx.org -- and currently @asantoni is generously paying :).

**Comment by rryan** [comment]
If ease of use is the main reason you were thinking -- we should make it easier for you to update the website :). Maybe a Fabric script so you can just type "fab push" to publish?

**Comment by esbrandt** [comment]
> Also we probably wouldn't get Google Analytics?

Apparently, this work: https://stackoverflow.com/questions/17207458/how-to-add-google-analytics-tracking-id-to-github-pages

> easier for you to update the website

Easier for all involved.
I dont want to push change for change's sake. Imo we still underestimate the importance of a proper translated web site. Now that we use Transifex, this can be easily a sub-project. But i see the issues with /wiki and /forums.

PS. Never guessed traffic costs were this low. Need more downloads:-)

**Comment by rryan** [comment]
Yea, hmm. I will think on how to make a translated site. We should ditch PHP and move to a proper static-file generator tool with templates. That way we could just translate the templates.

**Comment by esbrandt** [comment]
obsolete, we use cactus as static-file generator
