### ISSUE TITLE
Force HTTPS 

### ISSUE THREAD

**Issue by wesinator** [mixxxdj/website#137]
downloads.mixxx.org https is not forced, FYI

thanks for this open source software

**Comment by Be-ing** [comment]
Thanks for bringing this to our attention.

**Comment by Holzhaus** [comment]
Just noticed this issue. We should also implement a HSTS header:

https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

**Comment by rryan** [comment]
downloads.mixxx.org has an HTTPS redirect and HSTS now

**Comment by Be-ing** [comment]
This is solved now, correct? Reopen this if not.
