### ISSUE TITLE
Site of mixxx is out

### ISSUE THREAD

**Issue by reginaldojunior** [mixxxdj/website#168]
I try access site of project but is out. 

![Captura de tela de 2020-12-13 18-23-20](https://user-images.githubusercontent.com/7466894/102024362-55337800-3d70-11eb-8730-945781a63818.png)

**Comment by Be-ing** [comment]
We're aware. We're working on switching the site to a different host.

**Comment by reginaldojunior** [comment]
Oh Okay! I closed issue then. I See more later. Regards

**Comment by Holzhaus** [comment]
I reopened this until the issue is resolved.

**Comment by reginaldojunior** [comment]
Great! :partying_face:

**Comment by Be-ing** [comment]
Fixed.
