### ISSUE TITLE
Will a stable 2.3 be released before year 2021 starts?

### ISSUE THREAD

**Issue by 4tip** [mixxxdj/website#170]
Will a stable 2.3 be released before year 2021 starts or at least a updated 2.3 Beta-2 with less bugs then the first beta?

**Comment by Be-ing** [comment]
This is a bug tracker, not a forum. I already answered your question at https://github.com/mixxxdj/website/pull/86#issuecomment-744128013 If you have further questions, you can ask on the [forum](https://mixxx.discourse.group).
