### ISSUE TITLE
feed.xml link tag uses a relative path, breaking RSS detection on some pages

### ISSUE THREAD

**Issue by oznogon** [mixxxdj/website#195]
News articles are published to an Atom feed at https://mixxx.org/feed.xml, but in HTML across the site it links to a relative path:

```
    <link href="feed.xml" type="application/atom+xml" rel="alternate" title="Mixxx Atom Feed" />
```

This breaks RSS feed detection and links on, for instance, individual news articles because there's no `feed.xml` at `https://mixxx.org/news/feed.xml`.

**Steps to reproduce:**

1. Go to mixxx.org or build the site locally and serve it.
2. Go to any news article.
3. View page source, or click the "Feed" link under "About" in the footer.

_Expected behavior_

The link or link tag points to `/feed.xml`.

_Observed behavior_

The link or link tag points to `feed.xml`, which results in a 404.

**Comment by Holzhaus** [comment]
Should be fixed now, thanks for reporting.
