### ISSUE TITLE
Broken link to Paul Bloch of OpenArtist

### ISSUE THREAD

**Issue by deborahtrez** [mixxxdj/website#200]
I was reading this article from 2008. https://mixxx.org/news/2008-02-15-minor-website-revamp/

Where it says "We've also started using our new logo, created by [Paul Bloch of OpenArtist](http://openartist.net/)..." 
I think http://openartist.net/ could have moved or been renamed..... bcz this link leads to dead end. 

http://openartisthq.org/ is the closest match i could find.
@asantoni

**Comment by Holzhaus** [comment]
> http://openartisthq.org/ is the closest match i could find.

I don't think that's the correct website.

Maybe we can replace it with an archive.org link? Or we link to this site, which is the most recent mention of him I could find: https://git.opendesktop.org/openartist

**Comment by deborahtrez** [comment]
Do I have the permission to make this change to @asantoni's article?

**Comment by ywwg** [comment]
Yes, fixing a link is an acceptable edit to someone else's article

**Comment by deborahtrez** [comment]
Alright. Let me do that.
