### ISSUE TITLE
Fedora: Improve install instructions. 

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/website#218]
I have tried to install Mixxx on a fresh installed Fedora and I was a little lost. 

The orange download button leads me to the correct section of the download page. 

Than I am a bit lost with this: 

```
An RPM package for installation is available in the RPM Fusion repositories.

Please refer to RPM Fusion's instructions on how to enable the repositories on your system. Mixxx only requires enabling the free repository; the nonfree repository is not necessary for Mixxx.

RPM Fusion builds are maintained by the Mixxx development team. We support the next, the current, and selected previous Fedora release(s) if possible.
```
I have have finally managed to install Mixxx, but it was with peaking around. I am still unsure if this was the intended way. 
First I have added the free RPM Fusion rpm, which was easy. Than I read through the whole linked page with completely unrelated issue. The second link leads to a informative page but without obvious install instructions.  
Than I have searched the "Software" app, without success. 

I have finally tried: 
sudo dnf install mixxx

Which had success. 

I think we should update it to be on the same level than Ubuntu and Arch.

A bief instruction + a list of terminal commands that cover the default case. 

@uklotzde Can you share this step by step instruction?

**Comment by uklotzde** [comment]
I don't think that we should repeat the RPM Fusion installation instructions.

Mixxx then appears in GNOME Software as usual, at least after reloading the repository metadata. 

Unfortunately, the (inofficial and not recommended) *Flathub* installation source is preselected:

![Screenshot from 2021-03-18 23-09-23](https://user-images.githubusercontent.com/1474154/111704294-33e69a00-883f-11eb-8882-62686da4c8b6.png)

**Comment by uklotzde** [comment]
@Be-ing Ideas?

**Comment by Holzhaus** [comment]
Should we file a bug at gnome software?

**Comment by uklotzde** [comment]
We should add a direct link to https://rpmfusion.org/Configuration with the installation instructions. The landing page is really confusing.

**Comment by uklotzde** [comment]
Unfortunately, the Flathub sources are prioritized for other packages, too. Depends on the installation order, lexicographical order, or is intended.

RPM Fusion is just a 3rd party repo, so I guess Flathub is considered more relevant.

**Comment by Holzhaus** [comment]
So let's open a bug report. This priority shouldn't be hardcoded.

**Comment by Be-ing** [comment]
I think we should recommend users to install via dnf CLI and specifically warn against using GNOME Software.

**Comment by Be-ing** [comment]
Thank you for testing this. As experienced Fedora users it is easy for me and @uklotzde to overlook this.

**Comment by Be-ing** [comment]
I am doubtful asking upstream to deprioritize Flathub will go anywhere...

**Comment by Holzhaus** [comment]
> I am doubtful asking upstream to deprioritize Flathub will go anywhere...

It should be possible to specify a higher priority when adding the fusion repository IMHO.

**Comment by Be-ing** [comment]
I don't think they'll agree and I don't want to get into a prolonged discussion about this upstream...

**Comment by Be-ing** [comment]
It is inappropriate for Flatpaks to be prioritized above RPMs for audio software until they all work with PipeWire...

**Comment by daschuer** [comment]
My expectations is to have a step by step guide.
That I can follow without extra knowledge.
Referring to an external guide will work for me when we have a description that puts it into the mixxx context. Like use the Serato guide and replace Serato with Mixxx.

But actually I would prefer some shell command for copy and paste or even better s one click solution. That can't go wrong compared to a click here and here and here guide.

**Comment by Be-ing** [comment]
I agree, copying and pasting a few shell commands would be the easiest and most foolproof.

**Comment by Be-ing** [comment]
I think this should work:
```
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install mixxx
```
I will test in a fresh Fedora 34 VM.

**Comment by Be-ing** [comment]
I confirm copying and pasting those two lines into a shell works in a fresh Fedora 34 VM without any additional configuration.

**Comment by daschuer** [comment]
Does this also keep Mixxx updated?

**Comment by Be-ing** [comment]
Yes, `dnf update` will update Mixxx and everything else on the system.
