### ISSUE TITLE
download section: do not use all caps

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/website#244]
reported by @foss- https://bugs.launchpad.net/mixxx/+bug/1928766

Currently the download section uses all caps.

Better readability and easier on the eyes not using all caps.

And for unknown reasons Ubuntu is the only OS which also uses a codename. This is not the case for Windows, macOS or other Linux distributions so should probably be removed.

**Comment by ronso0** [comment]
the Ubuntu link mentions the codename because for their release number and codename are often treated equally so the codename is relevant for Ubuntu-related 'services', for example the repos are named, and users may recognize it better than the number.
debian also uses codenames for their release. that other OS don't have that is no reason to remove it from the Ubuntu link. you can open an issue to add "El Capitan" to the mac 10.11 link :)

**Comment by VARUN-009** [comment]
I wanna work on this issue. Please assign this to me and since I'm new to this repo so I request you to please guide me through.

**Comment by ronso0** [comment]
please take a look around if you're interested in fixing a bug. this one has been resolved by mixxxdj/mixxx#10415
