### ISSUE TITLE
macOS / windows dev snapshot is named '2.3' while it is 'main'

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/website#248]
![image](https://user-images.githubusercontent.com/5934199/124674840-d0e74480-debb-11eb-994e-a477a1c93103.png)

(8d75d839f4 was merged to main)

Also, let's show
`Otherwise, you can download individual packages [link to d/l server] and install them manually.`
for those OS, too, so users can also pick 2.3.1 builds, not just those of main.

**Comment by Holzhaus** [comment]
Looks like we need to tune our `git describe` flags.

**Comment by ronso0** [comment]
hmm.. the ~~stable~~ hehe, snapshot section still reads "2.3-...-githash", and clicking that leads to a merge to main.

**Comment by Holzhaus** [comment]
Almost had a heart attack, but I releaszid you mean the development snapshots section ;-)

Anyway, it's weird. I'll have another look.

**Comment by Holzhaus** [comment]
Ah, the fix was committed to the `2.3` branch and hadn't been merged into `main` yet. @ywwg's latest merge commit should take care of it, let's see.

**Comment by Holzhaus** [comment]
https://github.com/mixxxdj/mixxx/runs/3033732840?check_suite_focus=true#step:29:25

Looks like it works, but we have to wait for the CI builds to finish to make sure.

**Comment by ronso0** [comment]
> Almost had a heart attack, but I releaszid you mean the development snapshots section ;-)

whoopsy, hehe

**Comment by ronso0** [comment]
(just trying if the Close button still works. yep, it does)

**Comment by ronso0** [comment]
the builds are now named "2.4..."
Thanks you!

I'll Close this one and ooen another issue for the links to the d/l server (for testing 2.3.1 builds for example )
