### ISSUE TITLE
scratch2_enable control is listed incorrectly in the Mixxx 2.3 manual

### ISSUE THREAD

**Issue by bandwich** [mixxxdj/website#306]
https://manual.mixxx.org/2.3/en/chapters/appendix/mixxx_controls
https://manual.mixxx.org/2.3/en/mixxx-control

These two pages list a control object called scratch2_enabled, which is really scratch2_enable.

**Comment by ronso0** [comment]
Thanks for the heads-up, I pushed a fix https://github.com/mixxxdj/manual/commit/23415883ffb0a52e15b03b619495a7bbf544e13e

FYI the Mixxx manual has a separate issue tracker (https://github.com/mixxxdj/manual/issues), this is one is for the website.
