### ISSUE TITLE
update_new_date.py bug with /r/n files 

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/website#371]
There was a major hassle with the release block post, because our update_new_date.py was not able to handle /r/n formated files.

I think it is "normal" that blog writers just open a file with their favorite editor without taking care of encoding. Changing the encoding is not an easy task depending on the used editor. 

How do we want to fix it? Shall we add /r/n support to the script? Or shall we convert the Ile in the fly?

**Comment by Swiftb0y** [comment]
We can either leverage pre-commit to fix the line endings or git. afaik git on windows can be configured to automatically change line endings to plain LN on commit and I'm fairly certain this is even the default. So this is not something we should spend resources to work around and instead just rely on the preexisting tools to deal with that.
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#mixed-line-ending
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by Swiftb0y** [comment]
In other words: we should not start trying to handle CRLF files but instead prevent them ending up in the repo at all because AFAIK thats best practice in git repos.

**Comment by daschuer** [comment]
We have now the evidence, that it has happened and investigating the issue took more time than a fix will take. We just need to decide how? 

Pelican can handle both file ending. So there in no strict need to prevent /r/n entirely. 

All user side tools are not sufficient, since they can be easily bypassed by the GitHub GUI. 

We need also consider that changing the line or file encoding during a PR is hard to do for a non-developer. 

So I think we should just fix our script and carry on. 
What are alternatives?

**Comment by Eve00000** [comment]
hi, 
did the newline / carriage return gave an error on every line?
I used the previous blogpost as a start and that one didn't have that error (I presume), the pre-commit did run before push, but there were some suggestions and demanded changes...
Excuse me if I made a mistake, sorry for your wasted time

**Comment by Swiftb0y** [comment]
> All user side tools are not sufficient, since they can be easily bypassed by the GitHub GUI.

Sure, but even when authoring these post using the github web UI it still shouldn't bypass CI. So we could verify this on CI. 

> We need also consider that changing the line or file encoding during a PR is hard to do for a non-developer.

Well, most editors have reasonably user-friendly support to change the line endings of a file nowadays and even then, its only a quick `git config core.autocrlf true` to change git to handle it correctly. 

> So I think we should just fix our script and carry on.
> What are alternatives?

Outlined above. I'm concerned that other tools we rely on and don't have control over might break on CRLF endings. So I'm still concerned about introducing this inconsistency into the tree. 

> did the newline / carriage return gave an error on every line?

Not really, the problem is that the script that updates the blog post date and removes the draft status didn't deal with them properly, so thats why the blogpost didn't get published correctly after merging. 

> Excuse me if I made a mistake, sorry for your wasted time

Don't worry ;) The immediate fallout is resolved now. You're authoring the blog posts on windows, right? whats your `git config core.autocrlf` output?

**Comment by daschuer** [comment]
Blame Microsoft for not following Unix when deciding for a line end code ....

The issue here was that pelican can deal with \r\n and we had no issues in the PR preview.

The bug happens when our script adds the release date to the file. It misses \r\n support and has on top not enough safety checks. 

But anyway, the mess exists and we need to make sure programatucally that it does not happen again.

**Comment by Swiftb0y** [comment]
> Blame Microsoft for not following Unix when deciding for a line end code ....

Sure I am, but I'm not the only one, git is too, which is why the `autocrlf` option exists and is usually on by default on windows even IIRC.

**Comment by Swiftb0y** [comment]
anyways, I'll take care of both.

**Comment by Eve00000** [comment]
>You're authoring the blog posts on windows, right? whats your `git config core.autocrlf` output?

![afbeelding](https://github.com/user-attachments/assets/593d1166-0712-4c10-8726-479d2efb91ce)

**Comment by Swiftb0y** [comment]
thanks. This is WSL right?

**Comment by Eve00000** [comment]
no git bash

**Comment by Swiftb0y** [comment]
right, so what text editor are you using? Do you always use `git bash` to commit?

**Comment by Eve00000** [comment]
Notepad++ 
Yes always git bash ... except with the last blogpost had some problems (Jan had to do some fixes and remember the line between title and list) so I tried it also in the githubweb

**Comment by Swiftb0y** [comment]
interesting. Anyways, the script now replaces the line endings when reading the blogpost for fixing the date. #372

**Comment by Swiftb0y** [comment]
> Notepad++

Well, that and potentially bypassing the `autocrlf` might have been the problem then. I mean the issue did not occur with #360 so it must've been a fluke.

**Comment by Eve00000** [comment]
the last paragraph (replacing the big list of controller-updates with one sentence) was also a suggestion through the github interface whitch I commited.

**Comment by Swiftb0y** [comment]
Good to know, but I doubt that was the source of the `\r\n`s.
