### ISSUE TITLE
System requirements text for 2.5 stable is not correct

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/website#377]
The headlines of the drop downs are correct, but the detail text if you expand them is still from 2.4, e.g. :  "Intel macOS 10.12" is still mentioned under the correct headline "MACOS 11 or later“

**Comment by ronso0** [comment]
Fixed by 0f6da8e35a62ccdb1528b1f00446dab38e9a9fb8

I also updated the Source code version/link for 2.5
