### ISSUE TITLE
clean up top bar

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/website#59]
the top bar contains 'quick links' that also appear in Community and support and thereby appears crammed.
also, when used on a small screen (mobile device), hamburger menu is crammed and there's no disctinction between internal and external links

So are there any design objections to clean up the top bar by moving all community/support links to **Communit & Support** (and footer template)

**Comment by radusuciu** [comment]
I agree, less = more in this case. Can submit PR if you don't want it.
