### ISSUE TITLE
describe upgrade procedure

### ISSUE THREAD

**Issue by ywwg** [mixxxdj/website#61]
We regularly get questions on facebook about whether it's necessary to uninstall the old version before installing the new one.  We should put something on the download page that says it's ok to install the new version on top of the old one.

**Comment by ywwg** [comment]
(or maybe just put it on the wiki under https://mixxx.org/wiki/doku.php/troubleshooting ?)

**Comment by ronso0** [comment]
What about both?
A link on the download page to > upgrade issues (even if that's just "install the new version on top of the old one" + some backup tips?)

**Comment by ronso0** [comment]
I could include this in #62 if someone writes up the wiki text. ?

**Comment by ywwg** [comment]
I'll see if I can write something up tomorrow, if not don't block on me

**Comment by Holzhaus** [comment]
I think the most straightforward way would be to add it to the manual in the "Installing Mixxx" section IMHO.

**Comment by Holzhaus** [comment]
... and we should also link that manual section from the release announcement blog post.

**Comment by ywwg** [comment]
yeah I'll see if I can whip something up

**Comment by ywwg** [comment]
https://github.com/mixxxdj/manual/pull/114

**Comment by VARUN-009** [comment]
I wanna work on this issue. Please assign this to me and since I'm new to this repo so I request you to please guide me through.

**Comment by ronso0** [comment]
@VARUN-009 this issue has already been resolved by https://github.com/mixxxdj/manual/pull/114 just hasn't been marked as such
