### ISSUE TITLE
improve font design

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/website#76]
* split long texts into columns (like in most Features sections)
with short lines, following line-breaks requires much less attention. Less effort to navigate, more focus for actually reading

* relaxe font <> background contrast a bit
I find reading white text on black bg for a longer period quite stressing.
We can even use `#999999` for long text and still pass the [WCAG AAA test](https://webaim.org/resources/contrastchecker/)

![image](https://user-images.githubusercontent.com/5934199/78515008-7e007800-77b4-11ea-8d10-e27cf5b4d5b2.png)

before
![image](https://user-images.githubusercontent.com/5934199/78515026-953f6580-77b4-11ea-8e8d-4b13a8ea3eb0.png)

**Comment by Holzhaus** [comment]
LGTM.

**Comment by ronso0** [comment]
I'll take care of this during beta period.

**Comment by sblaisot** [comment]
Maybe we could keep titles in plain White. That would emphasis sections.
