### ISSUE TITLE
Unable to update translation template, configuration error?

### ISSUE THREAD

**Issue by esbrandt** [mixxxdj/website#9]
`cactus messages:make`

produces the 2 folders
- `e`
- `n`

instead of just one folder `en`

This is needed for updating the translation template b4 uploading to transifex.
Would like to have the website translated at launch, at least for some languages.

**Comment by rryan** [comment]
Hm, I can't reproduce. What version of Cactus? 

pip freeze for me says:

```
backports.ssl-match-hostname==3.4.0.2
boto==2.38.0
Cactus==3.0.2
certifi==2015.4.28
colorlog==2.6.0
Django==1.5.5
ecdsa==0.13
Fabric==1.10.1
keyring==5.3
markdown2==2.3.0
paramiko==1.15.2
pycrypto==2.6.1
tornado==4.1
```

**Comment by esbrandt** [comment]
Thanks for testing, have the the latest cactus 3.3.2 installed

```
alabaster==0.7.6
Babel==2.1.1
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
boto==2.38.0
Cactus==3.3.2
certifi==2015.11.20.1
click==6.2
colorama==0.3.5
colorlog==2.6.0
Django==1.6.11
django-markwhat==1.4
docutils==0.12
Jinja2==2.8
keyring==5.7.1
markdown2==2.3.0
MarkupSafe==0.23
polib==1.0.7
Pygments==2.0.2
pytz==2015.7
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.0
Sphinx==1.3.2
sphinx-intl==0.9.7
sphinx-rtd-theme==0.1.9
tornado==4.3
transifex-client==0.11
urllib3==1.12
wheel==0.26.0
```

Downgraded to your version `pip install cactus==3.0.2`

`cactus messages:make`
still gives...

```
...
processing locale e
processing locale n
```

Tried to change the branch to no avail

Could not find an related issue on their gh page.

**Comment by rryan** [comment]
Did you get this working?

**Comment by esbrandt** [comment]
I thought, but have not :(
For every char in the default locale config (https://github.com/mixxxdj/website/blob/website/config.json#L3)
 `cactus messages:make`
 produces a folder, ergo if locale= `en-us`, i get 5 folders.
For other configs (e.g. `config.de.json`) it do not produce an `*.po` output at all.

**Comment by esbrandt** [comment]
Got it, this works
- `pip uninstall cactus` (removes cactus 3.3.2)
- `pip install cactus==3.0.2` (installs cactus 3.0.2/ downgrades Django-1.6.11->Django-1.5.5)
- `cactus messages:make`
- Updated content in both folders `en`& `de-DE`

**Comment by rryan** [comment]
Oi, ok glad you got it figured out. I'll try upgrading to the latest Cactus at some point to see if I can reproduce.

**Comment by esbrandt** [comment]
Doo, still present win latest Cactus
```
$ pip show cactus
Name: Cactus
Version: 3.3.3
```
Turns out this is a bug in Cactus, see eudicots/Cactus/issues/263 , lists also a workaround.
Fix was submitted, but not merged yet, see eudicots/Cactus/pull/267

**Comment by esbrandt** [comment]
Again, one year passed, and v3.3.3 is still latest.
The patch mentioned in the last commit has been merged to master, but there is no new release available.

Cactus looks like a dead horse.

Edit: Manually copying to the correct folder, so that we at least have a recent template available for upload to Transifex.

**Comment by esbrandt** [comment]
We do not use Cactus any more. TG
