### ISSUE TITLE
Link to github

### ISSUE THREAD

**Issue by radusuciu** [mixxxdj/website#90]
I'm not sure a link to https://github.com/mixxxdj/mixxx is anywhere to be found currently

**Comment by Holzhaus** [comment]
Maybe we can just use a ribbon?
https://github.blog/2008-12-19-github-ribbons/

**Comment by radusuciu** [comment]
I like these for my own stuff, https://github.com/tholman/github-corners, but maybe not the best fit for Mixxx

**Comment by Holzhaus** [comment]
We now have links to GitHub on the index splash, the download page and in each page footer.
